version: 2
project_name: epever-solar
before:
  hooks:
    - go mod download
    - go mod tidy
    - go generate ./...
builds:
  - id: epever-solar
    main: ./tools/cli
    binary: epever-solar
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{ if index .Env "VERSION" }}{{ .Env.VERSION }}{{ else }}{{ .Version }}{{ end }}
archives:
  - formats:
      - zip
nfpms:
  - maintainer: Nick Ng <ngyewch@gmail.com>
    description: EPEVER Solar Charge Controller utility
    formats:
      - deb
      - rpm
checksum:
  name_template: 'checksums.txt'
changelog:
  disable: true
release:
  disable: false
